# -*- coding: utf-8 -*-
"""Copy of numpy_tutorial_by_Rishabh_Mishra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhpaOQPg4crc7QZ7-fIk7Pcg2-4oZwxA

## Numpy Tutorial by Rishabh Mishra
"""

# Numpy Full Course: https://www.youtube.com/watch?v=uaTigVkG2dk

# Install Numpy
!pip install numpy

# Import Numpy library
import numpy as np

print(np.__version__) # Numpy version installed in the system

"""#### 1. creating arrays  """

list1 = [1,2,3]
print(list1)

arr_list1 = np.array(list1) # creating array using list
print(arr_list1)

print(type(arr_list1))  # check data type of variable

print(arr_list1.ndim)   # check dimension of array

# creating 2-dim array using 2 lists
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

print(arr_list1_2.ndim) # check dimension of array

# creating 3-dim array using 3 lists
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1, list2, list3]])
print(arr_list1_3)

print(arr_list1_3.ndim)     # check dimension of array

"""#### 2. numpy array attributes"""

arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

# Attributes of Array (properties of array)
print("Shape", arr1.shape)  # share= rows, columns and height of array
print("Size", arr1.size)    # number of elements in array
print("dType", arr1.dtype)  # data type of elements in array
print("n_dim", arr1.ndim)   # dimension of array

# HW: create two arrays - 1D and 3D, and find it's attributes

"""#### 3. Array initialization methods"""

# zeros array : all elements are 0

zero_arr = np.zeros((2,3))
print(zero_arr)

# ones array : all elements are 1

one_arr = np.ones((1,3))
print(one_arr)

# Full array : all elements are same based on given value

full_arr = np.full((3,2), 9)
print(full_arr)

# Identity Matrix : diagonal elements are ones and all other elements are zeros

id_arr = np.eye(3)
print(id_arr)

# empty array
print(np.empty(2))

# evenly spaced array : elements are evenly spaced based on step value
print(np.arange(2,10,2))

# specific number of eqaully spaced values between a range : elements are equally spaced based on step value
print(np.linspace(1,10,4))

# random values array - float
r_arr = np.random.rand(3,2)
print(r_arr)

# random values array - int
rint_arr = np.random.randint(1,100,(3,3))
print(rint_arr)

"""#### 4 Array Indexing and Slicing"""

a = np.array([1,3,5,7,9])
print(a)

print(a[0])     # first element of array

print(a[4])     # fifth element of array

print(a[-1])      # last element of array

a = np.array([1,3,5,7,9])
print(a)
# Slicing :
# array[start:stop:step]
# stop - index, that is not included in output

print(a[0:3]) # First 3 elements

print(a[-3:]) # Last 3 elements

print(a[1:4]) # Middle 3 elements

print(a[0::3]) # Middle 3 elements with steps

print(a[0::2]) # All alternative elements with steps

# Indexing on 2 Dimensional Array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

# 2D Array: [rows, columns]                   # 2D Array takes 2 values - rows and columns for indexing
# 3D Array: [layers/height, rows, columns]    # 3D Array takes 3 values - height, rows and columns for indexing

print(arr2[0]) # first row
print(arr2[1]) # second row

# Slicing on 2D array
print(arr2[0][0]) # element of first row and first column
print(arr2[0][1]) # element of first row and second column
print(arr2[1][2]) # element of second row and third column

print(arr2[1]) # specific element - 1D
print(arr2[1:]) # slicing part - 2D

print(arr2)

# 2D Array: [rows, columns]  |  eg: arr2[0][1]     # 2D Array takes 2 values - rows and columns for indexing

print(arr2[:, 0])       # First column of an array
print(arr2[:, 1])       # Second column of an array
print(arr2[:, 2])       # Third column of an array

arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)

# 3D Array: [layers/height, rows, columns]        # 3D Array takes 3 values - height, rows and columns for indexing

print(arr3[0])
print(arr3[1])
print(arr3[2])

print(arr3[0][2])
print(arr3[2][2])

print(arr3[:, 0]) # 1st col value
print(arr3[:, 1]) # 2nd col value
print(arr3[:, 2]) # 3rd col value

print(arr3[::, 1:2])  #slicing on columns
print(arr3[2::, 1:2]) #slicing on rows and columns

"""#### 5 Array Reshaping and Flattening"""

# Reshape Array: changing its dimensions (e.g., rows and columns) without altering the actual data
# Flatten Array: transforming a multi-dimensional array into a single-dimensional array

arr1 = np.array([1,2,3,4,5,6])      # shape = (1,6) - 1 row and 6 columns
print(arr1)

reshaped = arr1.reshape((6,1))      # shape = (6,1) - 6 rows and 1 column
print(reshaped)

reshaped2 = arr1.reshape((2,3))     # re-shaped array from (1,6) to (2,3)
print(reshaped2)

print(reshaped2.flatten())          # flattened array from higher (2D) dimensional (2,3) to (1,6) (1D)

"""#### 6 Array Stacking and Splitting"""

# Array Stacking:  combining multiple arrays along a new axis, resulting in an array with a higher dimension than the input arrays
# Array Splitting:

# stacking
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking - row wise          -> output array is 2D
print(np.hstack((a,b))) # horizontal stacking - column wise     -> output array is 1D

# splitting
c = np.array([[1,2,3], [4,5,6]])
print(c)

hsplit = np.hsplit(c,3) # horizontal split -> input and output array are same dimention

for s in hsplit:
    print(s)

vsplit = np.vsplit(c,2) # vertical split -> input and output array are same dimention

for s in vsplit:
    print(s)

"""#### 7 Mathematical Operations on Array"""

# Commented out IPython magic to ensure Python compatibility.
# # FYI: list vs Array
# # one of the reason we array instead of list : time taken by an operation on list is more >>>>> than array
# %%time
# numbers = list(range(1, 100000001))
# result = [x+5 for x in numbers]

# Commented out IPython magic to ensure Python compatibility.
# %%time
# numbers = np.arange(1,100000001)
# result = numbers+5

a = np.array([10,20,40,-30])
print(a)

print(a+10) # add a value in array
print(a-30) # subs a value in array
print(a*2) # multiply by a value in array
print(a/10) # divide by a value in array

b = np.array([1,4,9])
print(b)

print(np.square(b)) # square of all array elements
print(np.sqrt(b))   # square root of all array elements

# HW: sin, tan, cos, sec

"""#### 8 Mathematical Operations on Muliple Arrays"""

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

print(np.add(a,b))          # add two arrays
print(np.subtract(a,b))     # subtract two arrays
print(np.multiply(a,b))     # multiply two arrays
print(np.divide(a,b))       # divide two arrays

# Dot product: computes the inner product of the two vectors and sum the results
print(np.dot(a,b)) # dot product

print(a.T) # Transpose: Returns an array with axes transposed

t = np.array([[1,2,3],
              [4,5,6]])

print(t)    # initial shape: 2,3
print(t.T)  # shape after transpose: 3,2

"""#### 9 Statistical Functions"""

a = np.array([[1,2,3], [4,5,6]])
print(a)

print(np.sum(a))    # sum of all elements of an array

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

"""#### 10 Array Comparison"""

a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

print(a == b) # comparing each elements of an array
print(np.array_equal(a,b)) # comparing complete array

"""#### 11 Broadcasting"""

# Broadcasting: is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes,
# it eliminates the need for explicit loops or reshaping operations, making code more concise, readable and efficient.

# Broadcasting Rules:
    # Compare shapes from right to left.
    # Dimensions must match or be 1.
    # If one array has fewer dimensions, pad its shape on the left with 1s.
    # Any dimension equal to 1 can stretch to match the other array.

a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)      # adding 1D with 0ne-element array to 1D with multi-element array

c = np.array([[1,2,3], [4,5,6]])
d = np.array([10,20,30])
print(c+d)      # adding 2D with 6-element array (2,3) to 1D with 6-element array

"""#### 12 Handling with nan & inf"""

data1 =  np.array([1,2, np.nan, 4, np.inf])
print(data1)

print(np.isnan(data1))  # check null value and returns boolean value

print(np.nan_to_num(data1))    # replace non-finite values within an array with specified finite numbers

"""#### save and load arrays"""

arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy', arr)

loaded_arr = np.load('my_array.npy')
print(loaded_arr)

# Homework:
# 1. Create 5X5 matrix with values from 1 to 25
  # > extract last row
  # > first column
  # > sub matrix containing 3X3

# 2. Broadcasting: multiply shape- (3,1) matrix with shape- (3,)

# Free Data Analytics Resources: https://www.rishabhnmishra.com/notes

# Next Recommended Courses: Pandas and Matplotlib

